### ISSUE TITLE
Mock Google Auth Credentials for unit tests

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/alloydb-java-connector#314]
Currently the `units` and `windows` CI builds require valid Google auth credentials as a dependency for tests to succeed. We should mock the credentials so that the unit tests can pass in any environment and not depend on valid creds.

Part of this PR should be to disable auth setup in `units` and `windows` builds for pull requests, allowing for faster builds.

```yaml
- name: Authenticate to Google Cloud
    # only needed for Flakybot on periodic (schedule) and continuous (push) events
    if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
    uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
```
